# Generated by Django 4.2.1 on 2023-05-23 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_categoria_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('fechaNacimiento', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='crud.genero')),
            ],
        ),
    ]
