# Generated by Django 4.2.1 on 2023-05-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.IntegerField(unique=True),
        ),
    ]
